### ISSUE TITLE
Python plugins and API

### ISSUE THREAD

**Issue by eXeGOODER** [SkinN/RustPlugins#1]
Hello.
I see that your plug-ins are written on Python, I would be not against if you help me.
I don't know as to cause function from other API.

``` Python
PopupMsg_API = plugins.Find("PopupNotifications")
PopupMsg_API.Call( ..arguments.. )
```

**Comment by SkinN** [comment]
I am not sure what you are asking me exacly.

**Comment by SkinN** [comment]
By the way, I am sorry for the late answer.
